title: Your awesome title
author: Rahma Al-Wadhahi
email: rahma.wadhahi@phaze.ro
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. This is
  a testing blog with jekyll and gh-pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Rahma-AlWadhahi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
